# Factal Env

In [5]:
import numpy as np
import pandas as pd

In [ ]:


a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [2]:
b = np.array([[1, 2], [3, 4]])
print(b)

[[1 2]
 [3 4]]


In [3]:
c = np.vectorize(lambda x: x**2)
print(c(a))

[1 4 9]


In [6]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print(df)

   A  B
0  1  4
1  2  5
2  3  6
